# Generated by Django 4.2.6 on 2023-10-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=300)),
                ('sname', models.CharField(max_length=300)),
                ('scontact', models.CharField(max_length=300)),
            ],
        ),
    ]
